import { writeBatch, doc, Timestamp } from "firebase/firestore";
import { db } from "./Firebase";

const seededAt = Timestamp.fromDate(new Date("2026-03-31T12:00:00Z"));

export async function seedMockData() {
  const batch = writeBatch(db);

  const docs = [
    {
      path: ["wineResults", "wine_001"],
      data: {
        wineId: "wine_001",
        name: "Barolo DOCG 2019",
        producer: "Cantina Alba",
        vintage: 2019,
        category: "red",
        region: "Piemonte",
        appellation: "Barolo DOCG",
        country: "Italy",
        grapeVarieties: ["Nebbiolo"],
        imageUrl: "/images/barolo-docg-2019.png",
        answerKey: {
          wineName: "Barolo",
          region: "Piemonte",
          grapeVarieties: ["Nebbiolo"],
        },
        isActive: true,
        sortOrder: 1,
      },
    },
    {
      path: ["wineResults", "wine_002"],
      data: {
        wineId: "wine_002",
        name: "Etna Rosso 2021",
        producer: "Vulcano Wines",
        vintage: 2021,
        category: "red",
        region: "Sicilia",
        appellation: "Etna Rosso DOC",
        country: "Italy",
        grapeVarieties: ["Nerello Mascalese"],
        imageUrl: "/images/etna-rosso-2021.png",
        answerKey: {
          wineName: "Etna Rosso",
          region: "Sicilia",
          grapeVarieties: ["Nerello Mascalese"],
        },
        isActive: true,
        sortOrder: 2,
      },
    },
    {
      path: ["wineResults", "wine_003"],
      data: {
        wineId: "wine_003",
        name: "Chianti Classico 2020",
        producer: "Tenuta Fiorentina",
        vintage: 2020,
        category: "red",
        region: "Toscana",
        appellation: "Chianti Classico DOCG",
        country: "Italy",
        grapeVarieties: ["Sangiovese"],
        imageUrl: "/images/chianti-classico-2020.png",
        answerKey: {
          wineName: "Chianti Classico",
          region: "Toscana",
          grapeVarieties: ["Sangiovese"],
        },
        isActive: true,
        sortOrder: 3,
      },
    },
    {
      path: ["wineResults", "wine_004"],
      data: {
        wineId: "wine_004",
        name: "Amarone della Valpolicella 2018",
        producer: "Valle Verona",
        vintage: 2018,
        category: "red",
        region: "Veneto",
        appellation: "Amarone della Valpolicella DOCG",
        country: "Italy",
        grapeVarieties: ["Corvina", "Rondinella"],
        imageUrl: "/images/amarone-2018.png",
        answerKey: {
          wineName: "Amarone",
          region: "Veneto",
          grapeVarieties: ["Corvina", "Rondinella"],
        },
        isActive: true,
        sortOrder: 4,
      },
    },
    {
      path: ["wineResults", "wine_005"],
      data: {
        wineId: "wine_005",
        name: "Franciacorta Brut NV",
        producer: "Lago Spumanti",
        vintage: null,
        category: "sparkling",
        region: "Lombardia",
        appellation: "Franciacorta DOCG",
        country: "Italy",
        grapeVarieties: ["Chardonnay", "Pinot Nero"],
        imageUrl: "/images/franciacorta-brut.png",
        answerKey: {
          wineName: "Franciacorta Brut",
          region: "Lombardia",
          grapeVarieties: ["Chardonnay", "Pinot Nero"],
        },
        isActive: true,
        sortOrder: 5,
      },
    },
    {
      path: ["wineResults", "wine_006"],
      data: {
        wineId: "wine_006",
        name: "Prosecco Superiore DOCG",
        producer: "Colline Venete",
        vintage: null,
        category: "sparkling",
        region: "Veneto",
        appellation: "Conegliano Valdobbiadene Prosecco Superiore DOCG",
        country: "Italy",
        grapeVarieties: ["Glera"],
        imageUrl: "/images/prosecco-superiore.png",
        answerKey: {
          wineName: "Prosecco",
          region: "Veneto",
          grapeVarieties: ["Glera"],
        },
        isActive: true,
        sortOrder: 6,
      },
    },
    {
      path: ["wineResults", "wine_007"],
      data: {
        wineId: "wine_007",
        name: "Verdicchio dei Castelli di Jesi 2023",
        producer: "Marche Bianco",
        vintage: 2023,
        category: "white",
        region: "Marche",
        appellation: "Verdicchio dei Castelli di Jesi DOC",
        country: "Italy",
        grapeVarieties: ["Verdicchio"],
        imageUrl: "/images/verdicchio-2023.png",
        answerKey: {
          wineName: "Verdicchio",
          region: "Marche",
          grapeVarieties: ["Verdicchio"],
        },
        isActive: true,
        sortOrder: 7,
      },
    },
    {
      path: ["wineResults", "wine_008"],
      data: {
        wineId: "wine_008",
        name: "Soave Classico 2023",
        producer: "Monte Soave",
        vintage: 2023,
        category: "white",
        region: "Veneto",
        appellation: "Soave Classico DOC",
        country: "Italy",
        grapeVarieties: ["Garganega"],
        imageUrl: "/images/soave-classico-2023.png",
        answerKey: {
          wineName: "Soave",
          region: "Veneto",
          grapeVarieties: ["Garganega"],
        },
        isActive: true,
        sortOrder: 8,
      },
    },
    {
      path: ["wineResults", "wine_009"],
      data: {
        wineId: "wine_009",
        name: "Etna Bianco 2023",
        producer: "Terre Laviche",
        vintage: 2023,
        category: "white",
        region: "Sicilia",
        appellation: "Etna Bianco DOC",
        country: "Italy",
        grapeVarieties: ["Carricante"],
        imageUrl: "/images/etna-bianco-2023.png",
        answerKey: {
          wineName: "Etna Bianco",
          region: "Sicilia",
          grapeVarieties: ["Carricante"],
        },
        isActive: true,
        sortOrder: 9,
      },
    },
    {
      path: ["wineResults", "wine_010"],
      data: {
        wineId: "wine_010",
        name: "Cerasuolo d’Abruzzo 2023",
        producer: "Abruzzo Rosato",
        vintage: 2023,
        category: "rose",
        region: "Abruzzo",
        appellation: "Cerasuolo d’Abruzzo DOC",
        country: "Italy",
        grapeVarieties: ["Montepulciano"],
        imageUrl: "/images/cerasuolo-2023.png",
        answerKey: {
          wineName: "Cerasuolo d’Abruzzo",
          region: "Abruzzo",
          grapeVarieties: ["Montepulciano"],
        },
        isActive: true,
        sortOrder: 10,
      },
    },
    {
      path: ["wineResults", "wine_011"],
      data: {
        wineId: "wine_001",
        name: "Etna Rosso",
        producer: "",
        vintage: null,
        category: "red",
        region: "Sicilia",
        appellation: "Etna Rosso DOC",
        country: "Italy",
        grapeVarieties: ["Nerello Mascalese"],
        imageUrl: "/images/etna-rosso.png",
        answerKey: {
          wineName: "Etna Rosso",
          region: "Sicilia",
          grapeVarieties: ["Nerello Mascalese"],
        },
        isActive: true,
        sortOrder: 1,
      },
    },
  
    {
      path: ["wineResults", "wine_012"],
      data: {
        wineId: "wine_002",
        name: "Nero d'Avola",
        producer: "",
        vintage: null,
        category: "red",
        region: "Sicilia",
        appellation: "Sicilia DOC",
        country: "Italy",
        grapeVarieties: ["Nero d’Avola"],
        imageUrl: "/images/nero-davola.png",
        answerKey: {
          wineName: "Nero d'Avola",
          region: "Sicilia",
          grapeVarieties: ["Nero d’Avola"],
        },
        isActive: true,
        sortOrder: 2,
      },
    },
  
    {
      path: ["wineResults", "wine_013"],
      data: {
        wineId: "wine_003",
        name: "Grillo",
        producer: "",
        vintage: null,
        category: "white",
        region: "Sicilia",
        appellation: "Sicilia DOC",
        country: "Italy",
        grapeVarieties: ["Grillo"],
        imageUrl: "/images/grillo.png",
        answerKey: {
          wineName: "Grillo",
          region: "Sicilia",
          grapeVarieties: ["Grillo"],
        },
        isActive: true,
        sortOrder: 3,
      },
    },
  
    {
      path: ["wineResults", "wine_014"],
      data: {
        wineId: "wine_004",
        name: "Vermentino di Gallura",
        producer: "",
        vintage: null,
        category: "white",
        region: "Sardegna",
        appellation: "Vermentino di Gallura DOCG",
        country: "Italy",
        grapeVarieties: ["Vermentino"],
        imageUrl: "/images/vermentino-di-gallura.png",
        answerKey: {
          wineName: "Vermentino di Gallura",
          region: "Sardinia",
          grapeVarieties: ["Vermentino"],
        },
        isActive: true,
        sortOrder: 4,
      },
    },
  
    {
      path: ["wineResults", "wine_015"],
      data: {
        wineId: "wine_005",
        name: "Cannonau",
        producer: "",
        vintage: null,
        category: "red",
        region: "Sardegna",
        appellation: "Cannonau di Sardegna DOC",
        country: "Italy",
        grapeVarieties: ["Cannonau"],
        imageUrl: "/images/cannonau.png",
        answerKey: {
          wineName: "Cannonau",
          region: "Sardegna",
          grapeVarieties: ["Cannonau"],
        },
        isActive: true,
        sortOrder: 5,
      },
    },
  
    {
      path: ["wineResults", "wine_016"],
      data: {
        wineId: "wine_006",
        name: "Vernaccia di Oristano",
        producer: "",
        vintage: null,
        category: "special",
        region: "Sardegna",
        appellation: "Vernaccia di Oristano DOC",
        country: "Italy",
        grapeVarieties: ["Vernaccia"],
        imageUrl: "/images/vernaccia-di-oristano.png",
        answerKey: {
          wineName: "Vernaccia di Oristano",
          region: "Sardegna",
          grapeVarieties: ["Vernaccia"],
        },
        isActive: true,
        sortOrder: 6,
      },
    },
  
    {
      path: ["wineResults", "wine_017"],
      data: {
        wineId: "wine_007",
        name: "Cirò Bianco",
        producer: "",
        vintage: null,
        category: "white",
        region: "Calabria",
        appellation: "Cirò DOC Bianco",
        country: "Italy",
        grapeVarieties: ["Greco Bianco"],
        imageUrl: "/images/ciro-bianco.png",
        answerKey: {
          wineName: "Cirò Bianco",
          region: "Calabria",
          grapeVarieties: ["Greco Bianco"],
        },
        isActive: true,
        sortOrder: 7,
      },
    },
  
    {
      path: ["wineResults", "wine_018"],
      data: {
        wineId: "wine_008",
        name: "Cirò Rosato",
        producer: "",
        vintage: null,
        category: "rose",
        region: "Calabria",
        appellation: "Cirò DOC Rosato",
        country: "Italy",
        grapeVarieties: ["Gaglioppo"],
        imageUrl: "/images/ciro-rosato.png",
        answerKey: {
          wineName: "Cirò Rosato",
          region: "Calabria",
          grapeVarieties: ["Gaglioppo"],
        },
        isActive: true,
        sortOrder: 8,
      },
    },
  
    {
      path: ["wineResults", "wine_019"],
      data: {
        wineId: "wine_009",
        name: "Aglianico",
        producer: "",
        vintage: null,
        category: "red",
        region: "Campania",
        appellation: "Beneventano IGP",
        country: "Italy",
        grapeVarieties: ["Aglianico"],
        imageUrl: "/images/aglianico.png",
        answerKey: {
          wineName: "Aglianico",
          region: "Campania",
          grapeVarieties: ["Aglianico"],
        },
        isActive: true,
        sortOrder: 9,
      },
    },
  
    {
      path: ["wineResults", "wine_020"],
      data: {
        wineId: "wine_010",
        name: "Greco di Tufo",
        producer: "",
        vintage: null,
        category: "white",
        region: "Campania",
        appellation: "Greco di Tufo DOCG",
        country: "Italy",
        grapeVarieties: ["Greco"],
        imageUrl: "/images/greco-di-tufo.png",
        answerKey: {
          wineName: "Greco di Tufo",
          region: "Campania",
          grapeVarieties: ["Greco"],
        },
        isActive: true,
        sortOrder: 10,
      },
    },
  
    {
      path: ["wineResults", "wine_021"],
      data: {
        wineId: "wine_011",
        name: "Lambrusco DOC",
        producer: "",
        vintage: null,
        category: "sparkling",
        region: "Emilia-Romagna",
        appellation: "Lambrusco DOC",
        country: "Italy",
        grapeVarieties: ["Lambrusco Salamino", "Lambrusco Grasparossa", "Lambrusco Sorbara"],
        imageUrl: "/images/lambrusco-doc.png",
        answerKey: {
          wineName: "Lambrusco",
          region: "Emilia-Romagna",
          grapeVarieties: ["Lambrusco"],
        },
        isActive: true,
        sortOrder: 11,
      },
    },
  
    {
      path: ["wineResults", "wine_022"],
      data: {
        wineId: "wine_012",
        name: "Etna Rosato",
        producer: "",
        vintage: null,
        category: "rose",
        region: "Sicilia",
        appellation: "Etna Rosato DOC",
        country: "Italy",
        grapeVarieties: ["Nerello Mascalese"],
        imageUrl: "/images/etna-rosato.png",
        answerKey: {
          wineName: "Etna Rosato",
          region: "Sicilia",
          grapeVarieties: ["Nerello Mascalese"],
        },
        isActive: true,
        sortOrder: 12,
      },
    },
  
    {
      path: ["wineResults", "wine_023"],
      data: {
        wineId: "wine_013",
        name: "Trebbiano Spoletino Macerato",
        producer: "",
        vintage: null,
        category: "special",
        region: "Umbria",
        appellation: "Umbria IGT",
        country: "Italy",
        grapeVarieties: ["Trebbiano Spoletino"],
        imageUrl: "/images/trebbiano-spoletino-macerato.png",
        answerKey: {
          wineName: "Trebbiano Spoletino Macerato",
          region: "Umbria",
          grapeVarieties: ["Trebbiano Spoletino"],
        },
        isActive: true,
        sortOrder: 13,
      },
    },
  
    {
      path: ["wineResults", "wine_024"],
      data: {
        wineId: "wine_014",
        name: "Albana Frizzante",
        producer: "",
        vintage: null,
        category: "sparkling",
        region: "Emilia-Romagna",
        appellation: "Romagna DOC",
        country: "Italy",
        grapeVarieties: ["Albana"],
        imageUrl: "/images/albana-frizzante.png",
        answerKey: {
          wineName: "Albana Frizzante",
          region: "Emilia-Romagna",
          grapeVarieties: ["Albana"],
        },
        isActive: true,
        sortOrder: 14,
      },
    },
  ];

  for (const entry of docs) {
    const ref = doc(db, ...entry.path);
    batch.set(ref, entry.data, { merge: true });
  }

  await batch.commit();
  return docs.length;
}